default_topic_list:
  - "/scan_multi"
  - "/rplidar_laser_filter/scan_filtered"
  - "/ydlidar_laser_filter/scan_filtered"
  - "/imu/data"
  - "/carecules_odom"
  - "/odometry/filtered"
  - "/cmd_vel"
  - "/tf"
  - "/tf_static"
default_topic_list_with_cameras:
  - "/scan"
  - "/imu/data"
  - "/carecules_odom"
  - "/odometry/filtered"
  - "/cmd_vel"
  - "/pose_with_covariance_stamped"
  - "/pose2D"
  - "/tf"
  - "/tf_static"
  - "/camera/odom/sample"
  - "/camera/fisheye1/camera_info"
  - "/camera/fisheye1/image_raw"
  - "/camera/fisheye2/camera_info"
  - "/camera/fisheye2/image_raw"
  - "/camera/accel/imu_info"
  - "/camera/accel/sample"
  - "/camera/gyro/imu_info"
  - "/camera/gyro/sample"
